name: medical-image-ai
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - ipykernel
  - nodejs
  - opencv
  - pip
  - pip:
    - torch
    - monai
    - requests
    - itk==5.3.0
    - itkwidgets[all]==1.0a20
    - imjoy-jupyterlab-extension
    - pydicom
    - matplotlib
    - ipywidgets
